### ISSUE TITLE
List Open Symphony License separately

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [atifaziz/NCrontab#96] opened 2022-02-23 13:00 UTC
Hi there,

right now both licenses (Apache and Open Symphony) are included in the same file. Please add two separate files like `LICENSE-Apache-2.0` and `LICENSE-Open-Symphony-1.1` to make it visible that two licenses are used.

GitHub lists this project as only Apache-2.0 licensed.

Thank you,
Georg

**Comment by atifaziz** [comment] 2022-02-24 18:28
> GitHub lists this project as only Apache-2.0 licensed.

I usually don't let the hosting platform and UI drive these decisions.

As stated in `COPYING.txt`, the OpenSymphony Software License, Version 1.1, is derived and compatible with Apache License, Version 2.0:

https://github.com/atifaziz/NCrontab/blob/d47ad6cd32e68eb6753c8d904299b67982eeb960/COPYING.txt#L182-L183

I don't find there is anything to be gained or more clarity provided by separating the two.

I am going to close this issue, but if you have another argument then I would be happy to reconsider.

**Closed by atifaziz** 2022-02-24 18:28 UTC

**Comment by georg-eckert-zeiss** [comment] 2022-02-25 09:09
Thanks for your reply. As its impossible to fulfill all license requirements by hand in larger projects, many developers get help from FOSS scanners. In that case it's very useful if the license files are separated. Of course verifying the result is necessary, but this would make it easier.

Still your choice.

Best regards,
Georg : )

**Comment by atifaziz** [comment] 2022-02-26 15:39
The problem is that while splitting the file might satisfy some tools, it can hinder others. Right now, having one file makes it easier for packaging (for [review in nuget.org](https://www.nuget.org/packages/ncrontab/3.3.1/License)):

https://github.com/atifaziz/NCrontab/blob/9b68c8d1484ccd56a8f0bc1ce12e7270736f3493/NCrontab/NCrontab.csproj#L21

I wouldn't know how to workaround that and yet satisfy other tools people might be using the wild. I want keep this project low maintenance. Having one file, in case you are _redistributing publicly_ also makes it easier for redistribution.

I feel that tools should be made smarter so I would encourage you to contact the vendor or maintainer of the tool you're using.

For all intent and purposes, this software is distributed under the terms of **Apache License, Version 2.0**. The **OpenSymphony Software License, Version 1.1** has the special clauses 3, 4 and 5. Clauses 4 and 5 make sure you don't redistribute under certain (presumably) commercial names without written permission. Clause 3 requires an acknowledgement notice _if_ end-user documentation is included with the redistribution:

> This product includes software developed by the OpenSymphony Group (http://www.opensymphony.com/).

[That notice is included in the `README.md`](https://github.com/atifaziz/NCrontab/blame/9b68c8d1484ccd56a8f0bc1ce12e7270736f3493/README.md#L185) so you're covered whether you distribute it or not.

**Comment by georg-eckert-zeiss** [comment] 2022-02-28 08:06
Thank you for clarification : )
